version: '3.9'
services:
  backend-1:
    build: .
    image: sales:0.1
    restart: always
    environment:
      DJANGO_DEBUG: 0
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin_password
    ports:
    - "8000:8000"

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: salesuser
      POSTGRES_PASSWORD: securepassword
    volumes:
      - "./compose/pg_data:/var/lib/postgresql/data"