# Generated by Django 5.1 on 2024-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='period',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='sale_id',
            field=models.CharField(default='default_sale_id', max_length=255),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
