# Generated by Django 5.1 on 2024-09-09 12:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_project', '0002_remove_salesrecord_period_salesrecord_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_project.product'),
        ),
    ]
