# Generated by Django 5.1 on 2024-09-10 18:23

import sales_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_project', '0005_alter_salesfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesfile',
            name='file',
            field=models.FileField(upload_to='sales_files/', validators=[sales_project.models.validate_file_extension]),
        ),
    ]
