# Generated by Django 5.1 on 2024-09-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_project', '0006_alter_salesfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
