# Generated by Django 5.1.1 on 2024-09-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_project', '0007_supplierrecord_delete_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierrecord',
            name='product_id',
        ),
        migrations.AddField(
            model_name='supplierrecord',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_project.product'),
        ),
    ]
